# Top-level key for buildpacks
buildpacks:
  - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git

services:
  # A Web Service for the Python Backend
  - type: web
    name: youtube-downloader-backend
    env: python
    region: singapore
    rootDir: backend
    plan: free
    buildFilter:
      paths:
        - backend/**
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class gevent --timeout 120 --bind 0.0.0.0:$PORT app:app"